using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CIS479_Project3
{
    public enum Biozone { Aerial, Aquatic, Land };
    public enum Region { Unknown, KikoLake, Maraqua, Mystery_Island, Lutari_Island, Kraik_Island, Roo_Island, Tyrannia, TerrorMoutain,Kredulor, LostDesert, NeopiaCentral, Meridell, FearieLand };
    public enum Habitat { NotListed, Desert, Tropical, Meadows, Urban, Beaches, Oceans, Seas, Islands, Lakes, Forests, Moutains, Jungles, Space, Artic, Tundra, Sky };
    public enum Availability { Special, Rare, Common };
    public enum Kingdom { Mammal, Reptile, Dragon, Insect, Fish, Other, Bird, Alien };
    // Physical Traits
    public enum Sizes { Large, Medium, Small, Unknown };
    public enum WingType { Feathers, Webbed };
    public enum WingSize { Large, Small };
    public enum SnoutType { Beaked, Jawed, Trunked };
    public enum Diet { Unkown, Herbivore, Carnivore, Omnivore };
    public enum LegCount { None=0, Two=2, Four=4};
    public enum LegType { None, Paws, Hooves, Flippers, Other };
    public enum Hair { None, AllOver, Head, Mane, Neck, Back, Tail };
    // Personality Traits
    public enum Pers_T { Loyal, Mischevious, Playful, Lazy, Outgoing, Friendly, Shy, Sensitive, Adventureous, Lucky, Ferocious, Peaceful, Magical, Generous, Intelligent, Kind, Competitive, Brave, Courageous, Pacifist, Prissy, Foodie, Quick, Fieri };

    public class Neopets
    {
        public class Neopet {
            public string Name { get; set;  }
            public Biozone Biozone { get; set; } 
            public Availability Availability { get; set; } 
            public Region Region { get; set; } // 
            public List<Habitat> Habitats { get; set; } //
            public List<Pers_T> Personality_Traits { get; set; }
            public Phys_T Physical_Traits { get; set; }
            public Kingdom Kingdom { get; set; }
        }

        public class Phys_T {
            public Sizes Size { get; set; }
            public LegType LegType { get; set; }
            public LegCount Legs { get; set; }
            public bool Ears { get; set; }
            public bool Tail { get; set; }
            public bool Hooves { get; set; }
            public bool Hands { get; set; }
            public bool Allergies { get; set; }
            public bool Strong { get; set; }
            public bool Tusks { get; set; }
            public bool Horns { get; set; }
            public bool Nocturnal { get; set; }
            public List<Hair> Fur { get; set; }
            public bool Clawed { get; set; }
            public WingType? Wing_Type { get; set; }
            public WingSize? Wing_Size { get; set; }
            public SnoutType Snout { get; set; }
            public Diet? Diet { get; set; }
        }
        public static List<Neopet> Pets { get; set; }

        public Neopets() {
            Pets = new List<Neopet>() {
                new Neopet() {
                    Name = "Techo",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.NotListed },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Reptile,
                    Personality_Traits = { Pers_T.Playful, Pers_T.Outgoing, Pers_T.Friendly },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Hands = true,
                        LegType = LegType.Paws,
                        Legs = LegCount.Two,
                        Ears = false,
                        Tail = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.None },
                        Clawed = true,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Korbat",
                    Biozone = Biozone.Aerial,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Moutains, Habitat.Forests },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Bird,
                    Personality_Traits = { Pers_T.Playful, Pers_T.Outgoing, Pers_T.Friendly },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Legs = LegCount.Two,
                        LegType = LegType.Paws,
                        Ears = true,
                        Tail = true,
                        Hands = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = true,
                        Fur = { Hair.None },
                        Clawed = false,
                        Wing_Size = WingSize.Small,
                        Wing_Type = WingType.Webbed,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Jubjub",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.NotListed },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { Pers_T.Playful, Pers_T.Outgoing, Pers_T.Friendly },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Hands = false,
                        LegType = LegType.Paws,
                        Legs = LegCount.Two,
                        Ears = false,
                        Tail = false,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.Head },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Tuskaninny",
                    Biozone = Biozone.Aquatic,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Beaches, Habitat.Oceans, Habitat.Seas, Habitat.Islands },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Bird,
                    Personality_Traits = { Pers_T.Playful, Pers_T.Outgoing, Pers_T.Friendly },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Unknown,
                        Legs = LegCount.Two,
                        LegType = LegType.Flippers,
                        Ears = false,
                        Tail = true,
                        Hands = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.Head },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Zafara",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Artic, Habitat.Beaches, Habitat.Forests, Habitat.Islands, Habitat.Jungles, Habitat.Meadows, Habitat.Moutains, Habitat.Oceans, Habitat.Seas, Habitat.Sky, Habitat.Space, Habitat.Tropical, Habitat.Tundra, Habitat.Urban },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Other,
                    Personality_Traits = { Pers_T.Adventureous, Pers_T.Lucky,  },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Large,
                        Hands = true,
                        LegType = LegType.Paws,
                        Legs = LegCount.Two,
                        Ears = true,
                        Tail = true,
                        Allergies = false,
                        Strong = true,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.AllOver },
                        Clawed = false,
                        Wing_Size = WingSize.Large,
                        Wing_Type = WingType.Feathers,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Flotsam",
                    Biozone = Biozone.Aquatic,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Oceans, Habitat.Seas },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Fish,
                    Personality_Traits = { Pers_T.Adventureous, Pers_T.Quick },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Legs = LegCount.Two,
                        LegType = LegType.Flippers,
                        Ears = false,
                        Tail = true,
                        Hands = false,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = true,
                        Nocturnal = true,
                        Fur = { Hair.None },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Blumaroo",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Islands, Habitat.Tropical, Habitat.Jungles },
                    Region = Region.Roo_Island,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { Pers_T.Playful, Pers_T.Outgoing, Pers_T.Friendly },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Large,
                        Hands = true,
                        LegType = LegType.Paws,
                        Legs = LegCount.Two,
                        Ears = true,
                        Tail = true,
                        Allergies = false,
                        Strong = true,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.Head },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Xweetok",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Forests, Habitat.Jungles },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { Pers_T.Quick, Pers_T.Adventureous },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Unknown,
                        Legs = LegCount.Four,
                        LegType = LegType.Paws,
                        Ears = true,
                        Tail = true,
                        Hands = false,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.AllOver },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Grarrl",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Moutains },
                    Region = Region.Tyrannia,
                    Kingdom = Kingdom.Reptile,
                    Personality_Traits = { Pers_T.Ferocious },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Large,
                        Legs = LegCount.Two,
                        LegType = LegType.Paws,
                        Strong = true,
                        Ears = false,
                        Snout = SnoutType.Jawed,
                        Hands = true,
                        Tail = true,
                        Allergies = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.None },
                        Clawed = true,
                        Wing_Size = null,
                        Wing_Type = null,
                        Diet = Diet.Omnivore
                    }
                },
                new Neopet() {
                    Name = "Pteri",
                    Biozone = Biozone.Aerial,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Jungles, Habitat.Forests },
                    Region = Region.Tyrannia,
                    Kingdom = Kingdom.Bird,
                    Personality_Traits = { Pers_T.Playful, Pers_T.Outgoing, Pers_T.Friendly, Pers_T.Mischevious },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Legs = LegCount.Two,
                        LegType = LegType.Other,
                        Ears = false,
                        Tail = true,
                        Hands = false,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = {Hair.None },
                        Clawed = true,
                        Wing_Size = WingSize.Small,
                        Wing_Type = WingType.Feathers,
                        Snout = SnoutType.Beaked,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Nimmo",
                    Biozone = Biozone.Aquatic,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Oceans, Habitat.Seas, Habitat.Islands, Habitat.Beaches, Habitat.Lakes },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Reptile,
                    Personality_Traits = { Pers_T.Intelligent, Pers_T.Peaceful, Pers_T.Pacifist, Pers_T.Loyal, Pers_T.Quick },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Hands = false,
                        LegType = LegType.Paws,
                        Legs = LegCount.Four,
                        Ears = false,
                        Tail = false,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.None },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Aisha",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.NotListed },
                    Region = Region.NeopiaCentral,
                    Kingdom = Kingdom.Other,
                    Personality_Traits = { Pers_T.Magical },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Legs = LegCount.Four,
                        LegType = LegType.Other,
                        Ears = true,
                        Tail = true,
                        Hands = false,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.None },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Meercas",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Artic, Habitat.Beaches, Habitat.Forests, Habitat.Islands, Habitat.Jungles, Habitat.Meadows, Habitat.Moutains, Habitat.Tropical, Habitat.Tundra, Habitat.Urban },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { Pers_T.Mischevious, Pers_T.Playful, Pers_T.Quick },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Hands = true,
                        LegType = LegType.Paws,
                        Legs = LegCount.Two,
                        Ears = true,
                        Tail = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.AllOver },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Omnivore
                    }
                },
                new Neopet() {
                    Name = "Usul",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Forests, Habitat.Jungles },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { Pers_T.Loyal, Pers_T.Generous, Pers_T.Friendly, Pers_T.Outgoing },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Legs = LegCount.Two,
                        LegType = LegType.Paws,
                        Ears = true,
                        Tail = true,
                        Hands = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = true,
                        Nocturnal = true,
                        Fur = { Hair.AllOver },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Scorchio",
                    Biozone = Biozone.Aerial,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Urban },
                    Region = Region.NeopiaCentral,
                    Kingdom = Kingdom.Dragon,
                    Personality_Traits = { Pers_T.Friendly, Pers_T.Outgoing },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Large,
                        Hands = true,
                        LegType = LegType.Paws,
                        Legs = LegCount.Two,
                        Ears = false,
                        Tail = true,
                        Allergies = false,
                        Strong = true,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.None },
                        Clawed = true,
                        Wing_Size = WingSize.Large,
                        Wing_Type = WingType.Webbed,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Ogrin",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.NotListed },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { Pers_T.Shy, Pers_T.Intelligent },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Unknown,
                        Legs = LegCount.Four,
                        LegType = LegType.Hooves,
                        Ears = true,
                        Tail = true,
                        Hands = false,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.AllOver },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Carnivore
                    }
                },
                // Start Gnorbu
                new Neopet() {
                    Name = "Gnorbu",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.NotListed },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { Pers_T.Playful, Pers_T.Outgoing, Pers_T.Friendly, Pers_T.Kind },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Hands = false,
                        LegType = LegType.Paws,
                        Legs = LegCount.Four,
                        Ears = true,
                        Tail = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.Mane, Hair.Tail },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Peophin",
                    Biozone = Biozone.Aquatic,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Oceans, Habitat.Seas, Habitat.Lakes },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Other,
                    Personality_Traits = { Pers_T.Shy, Pers_T.Lucky, Pers_T.Magical },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Legs = LegCount.Two,
                        LegType = LegType.Hooves,
                        Ears = true,
                        Tail = true,
                        Hands = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = true,
                        Fur = { Hair.Mane },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Lupe",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.NotListed },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { Pers_T.Brave, Pers_T.Loyal },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Medium,
                        Hands = false,
                        LegType = LegType.Paws,
                        Legs = LegCount.Four,
                        Ears = true,
                        Tail = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.AllOver },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Yurble",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Forests },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { Pers_T.Outgoing, Pers_T.Foodie },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Unknown,
                        Legs = LegCount.Two,
                        LegType = LegType.Paws,
                        Ears = true,
                        Tail = true,
                        Hands = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.Head, Hair.Neck, Hair.Back },
                        Clawed = true,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Omnivore
                    }
                },
                new Neopet() {
                    Name = "Skeith",
                    Biozone = Biozone.Aerial,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Urban },
                    Region = Region.NeopiaCentral,
                    Kingdom = Kingdom.Dragon,
                    Personality_Traits = { Pers_T.Foodie, Pers_T.Lazy },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Large,
                        Hands = true,
                        LegType = LegType.Paws,
                        Legs = LegCount.Two,
                        Ears = true,
                        Tail = true,
                        Allergies = true,
                        Strong = true,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.None },
                        Clawed = true,
                        Wing_Size = WingSize.Small,
                        Wing_Type = WingType.Webbed,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Bruce",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Moutains, Habitat.Artic, Habitat.Tundra },
                    Region = Region.TerrorMoutain,
                    Kingdom = Kingdom.Bird,
                    Personality_Traits = { Pers_T.Playful, Pers_T.Competitive },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Medium,
                        Legs = LegCount.Two,
                        LegType = LegType.Paws,
                        Ears = false,
                        Tail = true,
                        Hands = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = true,
                        Nocturnal = true,
                        Fur = { Hair.None },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Beaked,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Eyrie",
                    Biozone = Biozone.Aerial,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Islands, Habitat.Tropical },
                    Region = Region.Mystery_Island,
                    Kingdom = Kingdom.Other,
                    Personality_Traits = { Pers_T.Intelligent, Pers_T.Adventureous, Pers_T.Playful, Pers_T.Ferocious },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Large,
                        Hands = false,
                        LegType = LegType.Paws,
                        Legs = LegCount.Four,
                        Ears = true,
                        Tail = true,
                        Allergies = false,
                        Strong = true,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.Mane, Hair.Tail },
                        Clawed = false,
                        Wing_Size = WingSize.Large,
                        Wing_Type = WingType.Feathers,
                        Snout = SnoutType.Beaked,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Buzz",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.NotListed },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Insect,
                    Personality_Traits = { Pers_T.Quick, Pers_T.Foodie },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Legs = LegCount.Two,
                        LegType = LegType.Other,
                        Ears = false,
                        Tail = true,
                        Hands = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.None },
                        Clawed = false,
                        Wing_Size = WingSize.Small,
                        Wing_Type = WingType.Webbed,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Herbivore
                    }
                },
                new Neopet() {
                    Name = "Gelert",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.NotListed },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { Pers_T.Loyal, Pers_T.Brave, Pers_T.Courageous },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Legs = LegCount.Four,
                        LegType = LegType.Paws,
                        Strong = false,
                        Ears = true,
                        Snout = SnoutType.Jawed,
                        Hands = false,
                        Tail = true,
                        Allergies = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.Head },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Kacheek",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Meadows },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { Pers_T.Shy, Pers_T.Friendly, Pers_T.Pacifist, Pers_T.Peaceful },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Legs = LegCount.Two,
                        LegType = LegType.Paws,
                        Ears = true,
                        Tail = true,
                        Hands = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.AllOver },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Ixi",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Urban },
                    Region = Region.Meridell,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { Pers_T.Adventureous },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Medium,
                        Hands = false,
                        LegType = LegType.Hooves,
                        Legs = LegCount.Four,
                        Ears = true,
                        Tail = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = true,
                        Nocturnal = false,
                        Fur = { Hair.AllOver },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Acara",
                    Biozone = Biozone.Aquatic,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Urban, Habitat.Beaches },
                    Region = Region.NeopiaCentral,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { Pers_T.Playful },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Legs = LegCount.Four,
                        LegType = LegType.Other,
                        Ears = true,
                        Tail = false,
                        Hands = false,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = true,
                        Nocturnal = false,
                        Fur = { Hair.AllOver },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Moehog",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Moutains },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { Pers_T.Competitive, Pers_T.Playful },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Large,
                        Hands = false,
                        LegType = LegType.Hooves,
                        Legs = LegCount.Four,
                        Ears = true,
                        Tail = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = true,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.Mane, Hair.Tail },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Quiggle",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Lakes },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Reptile,
                    Personality_Traits = { Pers_T.Playful, Pers_T.Foodie},
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Legs = LegCount.Two,
                        LegType = LegType.Other,
                        Ears = false,
                        Tail = false,
                        Hands = true,
                        Allergies = true,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = true,
                        Fur = { Hair.None },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Herbivore
                    }
                },
                new Neopet() {
                    Name = "Chia",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.NotListed },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Other,
                    Personality_Traits = { Pers_T.Friendly, Pers_T.Outgoing, Pers_T.Adventureous },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Medium,
                        Hands = true,
                        LegType = LegType.Paws,
                        Legs = LegCount.Two,
                        Ears = false,
                        Tail = false,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.Head },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Kyrii",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.NotListed },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { Pers_T.Outgoing, Pers_T.Friendly, Pers_T.Ferocious },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Legs = LegCount.Two,
                        LegType = LegType.Paws,
                        Ears = true,
                        Tail = true,
                        Hands = true,
                        Allergies = true,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.Head, Hair.Neck, Hair.Back, Hair.Tail },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Carnivore
                    }
                },
                //Start Bori
                new Neopet() {
                    Name = "Bori",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Moutains},
                    Region = Region.TerrorMoutain,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { Pers_T.Shy},
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Hands = false,
                        LegType = LegType.Paws,
                        Legs = LegCount.Four,
                        Ears = true,
                        Tail = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.AllOver },
                        Clawed = true,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Lenny",
                    Biozone = Biozone.Aerial,
                    Availability = Availability.Common,
                    Habitats = { Habitat.NotListed},
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Bird,
                    Personality_Traits = { Pers_T.Magical, Pers_T.Intelligent },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Medium,
                        Legs = LegCount.Two,
                        LegType = LegType.Other,
                        Ears = false,
                        Tail = true,
                        Hands = false,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.None },
                        Clawed = false,
                        Wing_Size = WingSize.Large,
                        Wing_Type = WingType.Feathers,
                        Snout = SnoutType.Beaked,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Kau",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Meadows},
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { Pers_T.Adventureous, Pers_T.Lucky},
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Medium,
                        Hands = false,
                        LegType = LegType.Hooves,
                        Legs = LegCount.Four,
                        Ears = true,
                        Tail = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = true,
                        Nocturnal = false,
                        Fur = { Hair.AllOver},
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Vandagyre",
                    Biozone = Biozone.Aerial,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Moutains },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Bird,
                    Personality_Traits = { Pers_T.Playful, Pers_T.Outgoing, Pers_T.Friendly, Pers_T.Kind },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Unknown,
                        Legs = LegCount.Two,
                        LegType = LegType.Paws,
                        Ears = false,
                        Tail = true,
                        Hands = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.Head },
                        Clawed = false,
                        Wing_Size = WingSize.Large,
                        Wing_Type = WingType.Feathers,
                        Snout = SnoutType.Beaked,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Uni",
                    Biozone = Biozone.Aerial,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Artic, Habitat.Beaches, Habitat.Forests, Habitat.Islands, Habitat.Jungles, Habitat.Meadows, Habitat.Moutains, Habitat.Oceans, Habitat.Seas, Habitat.Sky, Habitat.Space, Habitat.Tropical, Habitat.Tundra, Habitat.Urban },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { Pers_T.Prissy, Pers_T.Intelligent},
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Large,
                        Hands = false,
                        LegType = LegType.Hooves,
                        Legs = LegCount.Four,
                        Ears = true,
                        Tail = true,
                        Allergies = false,
                        Strong = true,
                        Tusks = false,
                        Horns = true,
                        Nocturnal = false,
                        Fur = { Hair.AllOver },
                        Clawed = false,
                        Wing_Size = WingSize.Small,
                        Wing_Type = WingType.Feathers,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Elephante",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Oceans, Habitat.Seas },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { Pers_T.Adventureous, Pers_T.Quick },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Legs = LegCount.Two,
                        LegType = LegType.Hooves,
                        Ears = true,
                        Tail = true,
                        Hands = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = true,
                        Horns = true,
                        Nocturnal = true,
                        Fur = { Hair.Tail },
                        Clawed = false,
                        Wing_Size = WingSize.Small,
                        Wing_Type = WingType.Feathers,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Wocky",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.NotListed },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { Pers_T.Adventureous, Pers_T.Brave },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Unknown,
                        Hands = false,
                        LegType = LegType.Paws,
                        Legs = LegCount.Four,
                        Ears = true,
                        Tail = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.AllOver},
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Shoyru",
                    Biozone = Biozone.Aerial,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Urban},
                    Region = Region.NeopiaCentral,
                    Kingdom = Kingdom.Dragon,
                    Personality_Traits = { Pers_T.Loyal, Pers_T.Fieri},
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Legs = LegCount.Two,
                        LegType = LegType.Paws,
                        Ears = true,
                        Tail = true,
                        Hands = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = true,
                        Nocturnal = false,
                        Fur = { Hair.None},
                        Clawed = false,
                        Wing_Size = WingSize.Large,
                        Wing_Type = WingType.Webbed,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Kougra",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Islands },
                    Region = Region.Mystery_Island,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { Pers_T.Friendly, Pers_T.Playful },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Medium,
                        Legs = LegCount.Four,
                        LegType = LegType.Paws,
                        Strong = false,
                        Ears = true,
                        Snout = SnoutType.Jawed,
                        Hands = false,
                        Tail = true,
                        Allergies = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.AllOver },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Diet = Diet.Unkown,
                    }
                },
                new Neopet() {
                    Name = "Mynci",
                    Biozone = Biozone.Land,
                    Availability = Availability.Common,
                    Habitats = { Habitat.Jungles, Habitat.Forests, Habitat.Islands },
                    Region = Region.Mystery_Island,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { Pers_T.Playful, Pers_T.Friendly, Pers_T.Mischevious },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Large,
                        Legs = LegCount.Two,
                        LegType = LegType.Paws,
                        Ears = true,
                        Tail = true,
                        Hands = true,
                        Allergies = false,
                        Strong = true,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = {Hair.AllOver },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Chomby",
                    Biozone = Biozone.Land,
                    Availability = Availability.Special,
                    Habitats = { Habitat.Meadows },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Reptile,
                    Personality_Traits = { Pers_T.Shy },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Medium,
                        Hands = false,
                        LegType = LegType.Other,
                        Legs = LegCount.Four,
                        Ears = false,
                        Tail = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.None },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Herbivore
                    }
                },
                new Neopet() {
                    Name = "Cybunny",
                    Biozone = Biozone.Land,
                    Availability = Availability.Special,
                    Habitats = { Habitat.Artic, Habitat.Tundra },
                    Region = Region.TerrorMoutain,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { Pers_T.Playful, Pers_T.Friendly },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Legs = LegCount.Four,
                        LegType = LegType.Paws,
                        Ears = true,
                        Tail = true,
                        Hands = false,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.AllOver },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Grundo",
                    Biozone = Biozone.Land,
                    Availability = Availability.Special,
                    Habitats = { Habitat.Space },
                    Region = Region.Kredulor,
                    Kingdom = Kingdom.Alien,
                    Personality_Traits = { Pers_T.Friendly, Pers_T.Foodie},
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Hands = true,
                        LegType = LegType.Other,
                        Legs = LegCount.Two,
                        Ears = true,
                        Tail = false,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.None },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Hissi",
                    Biozone = Biozone.Aerial,
                    Availability = Availability.Special,
                    Habitats = { Habitat.NotListed },
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Reptile,
                    Personality_Traits = { Pers_T.Playful, Pers_T.Friendly },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Legs = LegCount.None,
                        LegType = LegType.None,
                        Ears = false,
                        Tail = true,
                        Hands = false,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = true,
                        Fur = { Hair.None },
                        Clawed = false,
                        Wing_Size = WingSize.Large,
                        Wing_Type = WingType.Webbed,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Jetsam",
                    Biozone = Biozone.Aquatic,
                    Availability = Availability.Special,
                    Habitats = { Habitat.Oceans, Habitat.Seas},
                    Region = Region.Unknown,
                    Kingdom = Kingdom.Fish,
                    Personality_Traits = { Pers_T.Ferocious },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Hands = true,
                        LegType = LegType.Flippers,
                        Legs = LegCount.Two,
                        Ears = false,
                        Tail = true,
                        Allergies = false,
                        Strong = true,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.None },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Kiko",
                    Biozone = Biozone.Aquatic,
                    Availability = Availability.Special,
                    Habitats = { Habitat.Lakes },
                    Region = Region.KikoLake,
                    Kingdom = Kingdom.Fish,
                    Personality_Traits = { Pers_T.Playful},
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Medium,
                        Legs = LegCount.None,
                        LegType = LegType.None,
                        Ears = false,
                        Tail = false,
                        Hands = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.None },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                // Start Lutari
                new Neopet() {
                    Name = "Koi",
                    Biozone = Biozone.Aquatic,
                    Availability = Availability.Special,
                    Habitats = { Habitat.Lakes },
                    Region = Region.Maraqua,
                    Kingdom = Kingdom.Fish,
                    Personality_Traits = { Pers_T.Intelligent, Pers_T.Outgoing, Pers_T.Friendly },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Hands = false,
                        LegType = LegType.Flippers,
                        Legs = LegCount.Two,
                        Ears = false,
                        Tail = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.None },
                        Clawed = true,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Lutari",
                    Biozone = Biozone.Aquatic,
                    Availability = Availability.Special,
                    Habitats = { Habitat.Oceans, Habitat.Islands, Habitat.Seas },
                    Region = Region.Lutari_Island,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { Pers_T.Playful },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Unknown,
                        Legs = LegCount.Four,
                        LegType = LegType.Paws,
                        Ears = true,
                        Tail = true,
                        Hands = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = true,
                        Fur = { Hair.AllOver},
                        Clawed = true,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Poogle",
                    Biozone = Biozone.Land,
                    Availability = Availability.Special,
                    Habitats = { Habitat.Sky },
                    Region = Region.FearieLand,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = { },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Hands = false,
                        LegType = LegType.Paws,
                        Legs = LegCount.Four,
                        Ears = true,
                        Tail = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.None},
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Ruki",
                    Biozone = Biozone.Aquatic,
                    Availability = Availability.Special,
                    Habitats = { Habitat.Desert },
                    Region = Region.LostDesert,
                    Kingdom = Kingdom.Insect,
                    Personality_Traits = { },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Unknown,
                        Legs = LegCount.Four,
                        LegType = LegType.None,
                        Ears = false,
                        Tail = false,
                        Hands = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.None },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Tonu",
                    Biozone = Biozone.Land,
                    Availability = Availability.Special,
                    Habitats = { Habitat.Moutains},
                    Region = Region.TerrorMoutain,
                    Kingdom = Kingdom.Mammal,
                    Personality_Traits = {  },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Unknown,
                        Hands = false,
                        LegType = LegType.Paws,
                        Legs = LegCount.Four,
                        Ears = true,
                        Tail = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = false,
                        Fur = { Hair.Neck, Hair.Tail },
                        Clawed = false,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                new Neopet() {
                    Name = "Draik",
                    Biozone = Biozone.Aerial,
                    Availability = Availability.Rare,
                    Habitats = { Habitat.Urban},
                    Region = Region.Meridell,
                    Kingdom = Kingdom.Dragon,
                    Personality_Traits = { },
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Small,
                        Legs = LegCount.Two,
                        LegType = LegType.Paws,
                        Ears = true,
                        Tail = true,
                        Hands = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = true,
                        Fur = { Hair.None },
                        Clawed = false,
                        Wing_Size = WingSize.Large,
                        Wing_Type = WingType.Webbed,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
                 new Neopet() {
                    Name = "Krawk",
                    Biozone = Biozone.Aquatic,
                    Availability = Availability.Rare,
                    Habitats = { Habitat.Islands},
                    Region = Region.Kraik_Island,
                    Kingdom = Kingdom.Reptile,
                    Personality_Traits = { Pers_T.Loyal, Pers_T.Playful},
                    Physical_Traits = new Phys_T() {
                        Size = Sizes.Medium,
                        Legs = LegCount.Two,
                        LegType = LegType.Paws,
                        Ears = false,
                        Tail = true,
                        Hands = true,
                        Allergies = false,
                        Strong = false,
                        Tusks = false,
                        Horns = false,
                        Nocturnal = true,
                        Fur = { Hair.Head, Hair.Back },
                        Clawed = true,
                        Wing_Size = null,
                        Wing_Type = null,
                        Snout = SnoutType.Jawed,
                        Diet = Diet.Unkown
                    }
                },
            };
        }
    }
}
